name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Decode and create spec file
      env:
        SPEC_FILE_CONTENT: ${{ secrets.SPEC_FILE_CONTENT }}
      run: |
        echo $SPEC_FILE_CONTENT | base64 --decode > PHASe.spec
    
    - name: Build with PyInstaller
      run: pyinstaller your_spec_file.spec
    
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: YourApp
        path: dist/*.app
